In [1]:
import numpy as np

__Note:__ Different operations are elementwise with numpy

In [2]:
x = np.array([[1,1], [0,-1]])
y = np.array([[-1,2], [0,1]])
x + y

array([[0, 3],
       [0, 0]])

In [3]:
x - y

array([[ 2, -1],
       [ 0, -2]])

In [4]:
x*y

array([[-1,  2],
       [ 0, -1]])

Scalar is applied to each element in the array.

In [5]:
2*x

array([[ 2,  2],
       [ 0, -2]])

###  Element wise functions
---

In [6]:
x = np.linspace(-1,1,11)
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [8]:
y = np.sin(np.pi*x)
np.round(y,decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [9]:
np.add(np.sin(x)**2, np.cos(x)**2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Vectorize a function
---

In [10]:
# this work on scalar
def heaviside(x):
    return 1 if x > 0 else 0
heaviside(2)

1

In [11]:
heaviside(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [12]:
# vectorize it
heaviside = np.vectorize(heaviside)

In [13]:
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

#### How the `axis` works in aggregate functions
---

In [14]:
data = np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
data.sum()

45

In [16]:
data.sum(axis=0)

array([12, 15, 18])

In [17]:
data.sum(axis=1)

array([ 6, 15, 24])