In [1]:
import numpy as np

`np.where`: Chooses values from two arrays depending on the value of a condition array
---

In [2]:
x = np.linspace(-4,4,9)
x

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [3]:
np.where(x<0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

`np.select`: Chooses values from a list of arrays depending on a list of conditions.
---

In [4]:
np.select([x<-1, x<2, x >= 2], [x**2, x**3, x*2])

array([16.,  9.,  4., -1.,  0.,  1.,  4.,  6.,  8.])

`np.choose`: Chooses values from a list of arrays depending on the values of a given index array
---

In [5]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], [x**2, x**3, x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

`np.nonzero`: returns an array with indices of nonzero elements
---

In [8]:
np.nonzero(abs(x)>2) # return a tuple of indices that you can index the array

(array([0, 1, 7, 8], dtype=int64),)

In [9]:
x[ np.nonzero(abs(x)>2) ]

array([-4., -3.,  3.,  4.])

In [10]:
x[abs(x)>2]

array([-4., -3.,  3.,  4.])