In [1]:
import numpy as np

In [2]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a[1:-1] # second to last element

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# first five elements
a[:5]

array([0, 1, 2, 3, 4])

In [5]:
# last five elements
a[-5:]

array([ 6,  7,  8,  9, 10])

#### Multidimensional array
---

In [7]:
f = lambda m, n: n+10*m
A = np.fromfunction(f, (6,6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [8]:
# second column
A[:, 1]

array([ 1, 11, 21, 31, 41, 51])

In [9]:
# second row
A[1,:]

array([10, 11, 12, 13, 14, 15])

In [10]:
# upper half diagonal block matrix
A[:3, :3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [11]:
# every second element starting from 0, 0
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

**Note**: Subarrays are views of the original array and they refer to it. Thus, once you change the subarray the original is also changed.

In [12]:
B = A[1:5,1:5]
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [13]:
B[:,:] = 0
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

Using explicit copy:

In [14]:
C = B[1:3, 1:3].copy()
C

array([[0, 0],
       [0, 0]])

In [15]:
C[:,:]=1 # does not affect B
B, C

(array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]),
 array([[1, 1],
        [1, 1]]))