In [1]:
import numpy as np

In [3]:
a1 = np.array([1,2,3])

In [5]:
a1.ndim, a1.shape

(1, (3,))

In [6]:
a2 = np.array([[1,2], [-6,2]])

In [7]:
a2.ndim, a2.shape

(2, (2, 2))

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
a3 = 5.4*np.ones(7)
a4 = np.full(7, 5.4)
a3, a4

(array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4]),
 array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4]))

In [12]:
a5 = np.empty(5)
a5.fill(3.2)
a5

array([3.2, 3.2, 3.2, 3.2, 3.2])

In [13]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.linspace(0,9,10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
np.logspace(0,2,5) # 5 points between 10**0=1 to 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

#### **Meshgrid**

In [21]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X, Y = np.meshgrid(x,y)
X, Y

(array([[-1,  0,  1],
        [-1,  0,  1],
        [-1,  0,  1]]),
 array([[-2, -2, -2],
        [ 0,  0,  0],
        [ 2,  2,  2]]))

In [22]:
# copmute (x+y)**2 for all combinations of x, y
Z = (X+Y)**2
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

In [24]:
np.ones_like(x)

array([1, 1, 1])

#### __Matrix array__

In [25]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [27]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [29]:
np.diag(np.arange(0,10, 2))

array([[0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 8]])