In [2]:
import scipy.sparse as sp
import scipy.sparse.linalg

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
import networkx as nx

In [6]:
values = [1,2,3,4]
rows = [0,1,2,3]
cols = [1,3,2,0]

In [7]:
A = sp.coo_matrix((values, (rows, cols)), shape=[4,4])
A

<4x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in COOrdinate format>

In [8]:
A.shape, A.size, A.dtype, A.ndim

((4, 4), 4, dtype('int64'), 2)

In [9]:
A.data

array([1, 2, 3, 4])

In [11]:
A.nnz # no non zero

4

In [12]:
A.row, A.col

(array([0, 1, 2, 3], dtype=int32), array([1, 3, 2, 0], dtype=int32))

In [15]:
A.tocsr()

<4x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [16]:
A.toarray()

array([[0, 1, 0, 0],
       [0, 0, 0, 2],
       [0, 0, 3, 0],
       [4, 0, 0, 0]])

In [19]:
B = np.array([[1,2,0,0], [0,3,4,0], [0,0,5,6], [7,0,8,9] ])
B

array([[1, 2, 0, 0],
       [0, 3, 4, 0],
       [0, 0, 5, 6],
       [7, 0, 8, 9]])

In [20]:
B = sp.csc_matrix(B)
B.data

array([1, 7, 2, 3, 4, 5, 8, 6, 9])

In [21]:
B.indices

array([0, 3, 0, 1, 1, 2, 3, 2, 3], dtype=int32)

In [22]:
B.indptr

array([0, 2, 4, 7, 9], dtype=int32)

In [23]:
i=2

In [25]:
B.indptr[i], B.indptr[i+1]-1

(4, 6)