In [3]:
from scipy import interpolate
from numpy import polynomial as P
import numpy as np
from scipy import linalg
import matplotlib.pyplot as plt

### Polynomials
---

In [4]:
# representation of 1 + 2x + 3x**2
p1 = P.Polynomial([1,2,3])
p1

Polynomial([1., 2., 3.], domain=[-1,  1], window=[-1,  1])

In [5]:
# polynomials from roots
p2 = P.Polynomial.fromroots([-1,1])
p2

Polynomial([-1.,  0.,  1.], domain=[-1.,  1.], window=[-1.,  1.])

In [9]:
p1.roots(), p2.roots()

(array([-0.33333333-0.47140452j, -0.33333333+0.47140452j]), array([-1.,  1.]))

In [10]:
p1.coef, p1.domain, p1.window

(array([1., 2., 3.]), array([-1,  1]), array([-1,  1]))

In [12]:
# evaluating p1
p1(np.array([1.5, 2.5, 3.5]))

array([10.75, 24.75, 44.75])

In [13]:
# dividing two polynomials
p1 = P.Polynomial.fromroots([1,2,3])
p2 = P.Polynomial.fromroots([2])
p1, p2

(Polynomial([-6., 11., -6.,  1.], domain=[-1.,  1.], window=[-1.,  1.]),
 Polynomial([-2.,  1.], domain=[-1.,  1.], window=[-1.,  1.]))

In [14]:
p3 = p1//p2
p3

Polynomial([ 3., -4.,  1.], domain=[-1.,  1.], window=[-1.,  1.])

In [15]:
p3.roots()

array([1., 3.])

In [16]:
# Using Chebyshev polynomilas (https://en.wikipedia.org/wiki/Chebyshev_polynomials)
c1 = P.Chebyshev([1,2,3])
c1

Chebyshev([1., 2., 3.], domain=[-1,  1], window=[-1,  1])

In [17]:
c1.roots()

array([-0.76759188,  0.43425855])

In [18]:
c1 = P.Chebyshev.fromroots([-1, 1])
c1

Chebyshev([-0.5,  0. ,  0.5], domain=[-1.,  1.], window=[-1.,  1.])

In [19]:
# Legendre polynomials (https://en.wikipedia.org/wiki/Legendre_polynomials)
l1 = P.Legendre.fromroots([-1,1])
l1

Legendre([-0.66666667,  0.        ,  0.66666667], domain=[-1.,  1.], window=[-1.,  1.])