In [1]:
import numpy as np
from scipy import linalg as la
from scipy import optimize
import sympy
import matplotlib.pyplot as plt
sympy.init_printing()

### README
---

A standard approach to solve eigen value problem is $(A - I\lambda)x = 0$. This gives a polynomial equation of $N$th order whose $N$ roots give the $N$ eigenvalues. Once the eigenvalues are known, the equation $(A - I \lambda_n)x_n = 0 $ can be solved for the nth eigenvector $x_n$

In [3]:
A = np.array([[1,3,5], [3,5,3], [5,3,8]])
evals, evecs = la.eig(A)

In [4]:
evals

array([12.74788906+0.j, -1.89460254+0.j,  3.14671348+0.j])

In [5]:
evecs

array([[ 0.44457418,  0.89567896,  0.0106302 ],
       [ 0.46789478, -0.22208918, -0.85542438],
       [ 0.76382477, -0.38527341,  0.51781863]])

In [6]:
la.eigvals(A)

array([12.74788906+0.j, -1.89460254+0.j,  3.14671348+0.j])