In [1]:
import numpy as np

__Note:__ Different operations are elementwise with numpy

In [2]:
x = np.array([[1,1], [0,-1]])
y = np.array([[-1,2], [0,1]])
x + y

array([[0, 3],
       [0, 0]])

In [3]:
x - y

array([[ 2, -1],
       [ 0, -2]])

In [4]:
x*y

array([[-1,  2],
       [ 0, -1]])

Scalar is applied to each element in the array.

In [5]:
2*x

array([[ 2,  2],
       [ 0, -2]])

###  Element wise functions
---

In [6]:
x = np.linspace(-1,1,11)
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [7]:
y = np.sin(np.pi*x)
np.round(y,decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [8]:
np.add(np.sin(x)**2, np.cos(x)**2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Vectorize a function
---

In [9]:
# this work on scalar
def heaviside(x):
    return 1 if x > 0 else 0
heaviside(2)

1

In [10]:
heaviside(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [11]:
# vectorize it
heaviside = np.vectorize(heaviside)

In [12]:
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

#### How the `axis` works in aggregate functions
---

In [13]:
data = np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
data.sum()

45

In [15]:
data.sum(axis=0)

array([12, 15, 18])

In [16]:
data.sum(axis=1)

array([ 6, 15, 24])

### Operations on Arrays
---

In [17]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
data.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [19]:
# flip right to left
np.fliplr(data)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [22]:
# flip up to down
np.flipud(data)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [23]:
# rotate 90 degree
np.rot90(data)

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [28]:
#sort elements
data2 = np.random.rand(5,5)
print(data2)
np.sort(data2, axis=0)

[[0.0679539  0.57089602 0.7814817  0.38977762 0.27480033]
 [0.3776795  0.06466414 0.36320623 0.0232417  0.35209618]
 [0.11281755 0.87383839 0.76844952 0.28309709 0.48135613]
 [0.78661421 0.49968594 0.62353485 0.00961962 0.26246611]
 [0.50761976 0.80571164 0.37419117 0.63136507 0.75823475]]


array([[0.0679539 , 0.06466414, 0.36320623, 0.00961962, 0.26246611],
       [0.11281755, 0.49968594, 0.37419117, 0.0232417 , 0.27480033],
       [0.3776795 , 0.57089602, 0.62353485, 0.28309709, 0.35209618],
       [0.50761976, 0.80571164, 0.76844952, 0.38977762, 0.48135613],
       [0.78661421, 0.87383839, 0.7814817 , 0.63136507, 0.75823475]])