In [1]:
import numpy as np

In [2]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)

In [3]:
A = np.matrix(A)
B = np.matrix(B)

In [4]:
Ap = B*A*B.I

In [5]:
Ap

matrix([[ 3.98239576, -4.27436563,  0.89717098],
        [ 2.88309323, -3.1988887 ,  0.62020297],
        [ 2.53704876, -2.80970632,  0.29761303]])

In [7]:
x = np.array(np.arange(5))
x

array([0, 1, 2, 3, 4])

In [8]:
np.inner(x,x)

30

In [9]:
np.outer(x,x)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])