In [1]:
import numpy as np

In [2]:
data = np.array([[1,-1], [3,0]])

In [3]:
np.reshape(data, (1,4))

array([[ 1, -1,  3,  0]])

In [4]:
data.reshape(4
            )

array([ 1, -1,  3,  0])

In [5]:
data.flatten()

array([ 1, -1,  3,  0])

In [6]:
num = np.arange(5)
num

array([0, 1, 2, 3, 4])

In [7]:
np.vstack((num, num, num))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [8]:
np.hstack((num, num))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [9]:
num = num[:, np.newaxis]

In [10]:
np.hstack((num, num))

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [11]:
a = np.array([[1,0], [3,9]])
b = np.array([[-5, 4], [7,8]])

In [12]:
np.concatenate((a,b), axis=0)

array([[ 1,  0],
       [ 3,  9],
       [-5,  4],
       [ 7,  8]])

In [13]:
np.concatenate((a,b), axis=1)

array([[ 1,  0, -5,  4],
       [ 3,  9,  7,  8]])